import { ArrowDown, ArrowUpRight, Compass, Camera, Send, UserRound } from 'lucide-react';
const topics = [['01','Понять свою точку отсчёта','Текущая ситуация, жизненные сферы и вопросы к себе.'],['02','Самооценка и личные опоры','Ценности, представления о себе и привычные сценарии.'],['03','Окружение и отношения','Поддержка, личные границы и общение в период перемен.'],['04','От размышлений к действиям','Цели, ежедневная рефлексия и план следующих шагов.']];
function Socials(){return <div className="socials"><button disabled aria-label="Telegram — ссылка появится позже" title="Telegram — ссылка появится позже"><Send size={18}/></button><button disabled aria-label="Instagram — ссылка появится позже" title="Instagram — ссылка появится позже"><Camera size={18}/></button></div>}
function Draft({children}:{children:React.ReactNode}){return <span className="draft">{children}</span>}
export default function Home(){return <>
<a className="skip" href="#course">Перейти к содержанию</a>
<header className="header"><a className="brand" href="#course"><span className="brand-mark">д.</span><span>ДМИТРИЙ<small>ПРОЕКТ КУРСА</small></span></a><nav aria-label="Основное меню"><a href="#about">Об авторе</a><a href="#approach">Подход</a><a href="#program">Программа</a></nav><div className="header-end"><Socials/><a className="small-cta" href="#purchase">О курсе <ArrowUpRight size={17}/></a></div></header>
<main><section className="hero wrap" id="course"><div className="hero-top"><span className="eyebrow"><span className="dot"/>ОБРАЗОВАТЕЛЬНАЯ ПРОГРАММА САМОПОМОЩИ</span><Draft>Макет · тексты в разработке</Draft></div><div className="hero-grid"><div><p className="overline">КУРС ДМИТРИЯ / РАБОЧЕЕ НАЗВАНИЕ</p><h1>Личностный кризис.<br/><em>Новая точка<br/>отсчёта.</em></h1><p className="hero-description">[Здесь будет короткое описание курса: для кого он, какие темы раскрывает и как устроена самостоятельная практика.]</p><a className="button" href="#purchase">Узнать об участии <ArrowUpRight size={20}/></a><p className="hero-note">Образование и практика. Не лечение и не психотерапия.</p></div><div className="hero-art" aria-hidden="true"><div className="orbital"><i/><i/><i/><i/><span>↗</span></div><span className="art-caption">НОВАЯ ТОЧКА ОТСЧЁТА</span><span className="art-corner">01 — ∞</span></div></div><div className="facts"><div><small>ФОРМАТ</small><span>Онлайн-программа</span></div><div><small>ДЛИТЕЛЬНОСТЬ</small><span>Уточняется</span></div><div><small>НАЧАЛО</small><span>Дата появится позже</span></div><a href="#about" aria-label="Перейти к блоку об авторе"><ArrowDown size={21}/></a></div></section>
<section className="section wrap author" id="about"><div className="portrait"><span className="overline">АВТОР ПРОГРАММЫ</span><UserRound size={94} strokeWidth={0.7}/><span>Место для фотографии Дмитрия<small>Портрет будет добавлен после согласования</small></span></div><div className="author-copy"><span className="eyebrow">01 / ЗНАКОМСТВО</span><h2>Дмитрий.<br/><em>Автор и ведущий.</em></h2><Draft>Биография на согласовании</Draft><p className="placeholder">[Здесь будет история Дмитрия, его путь к созданию программы и личная мотивация делиться опытом.]</p><p className="placeholder">[Подтверждённые образование, опыт и квалификация — после предоставления информации автором.]</p><div className="author-bottom"><span>Больше об авторе в соцсетях<small>Ссылки появятся позже</small></span><Socials/></div></div></section>
<section className="approach" id="approach"><div className="wrap section"><div className="section-heading"><div><span className="eyebrow">02 / ПОДХОД</span><h2>Внимание к себе.<br/><em>Место для действия.</em></h2></div><div className="heading-note"><Draft>Черновик по интервью</Draft><p>Темы для обсуждения с автором. Содержание и формат практик ещё согласовываются.</p></div></div><div className="approach-grid">{[['01','Самонаблюдение','[Описание подхода к рефлексии: замечать свою ситуацию, потребности и привычные реакции.]'],['02','Регулярная практика','[Описание самостоятельных заданий, утренней постановки цели и вечернего подведения итогов.]'],['03','Личный маршрут','[Описание работы с ценностями, окружением и планом дальнейших действий.]']].map(([n,title,copy])=><article key={n}><span className="step">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="boundary"><Compass size={24}/><p>Программа посвящена самопомощи и жизненным ориентирам. Она не предназначена для диагностики или лечения заболеваний и не заменяет профессиональную помощь.</p></div></div></section>
<section className="section wrap program" id="program"><div><span className="eyebrow">03 / СОДЕРЖАНИЕ</span><h2>Что может войти<br/><em>в программу</em></h2><p className="muted">Предварительные направления по интервью Дмитрия. Это ещё не утверждённый учебный план.</p><Draft>Названия и наполнение — черновик</Draft></div><div className="topic-list">{topics.map(([n,title,copy])=><details key={n}><summary><span>{n}</span><h3>{title}</h3><span className="plus">+</span></summary><div className="topic-content"><p>{copy}</p><p className="placeholder">[Здесь появятся описание блока, упражнения и формат работы после согласования программы.]</p></div></details>)}</div></section>
<section className="wrap purchase" id="purchase"><div><span className="eyebrow">04 / УЧАСТИЕ</span><h2>Ваш следующий шаг.<br/><em>В своём темпе.</em></h2><p>[Здесь будет приглашение к участию и краткое описание того, что входит в стоимость программы.]</p><div className="purchase-meta"><span>Старт<b>Уточняется</b></span><span>Доступ к материалам<b>Уточняется</b></span></div></div><div className="purchase-card"><Draft>Набор пока не открыт</Draft><h3>Участие в программе</h3><p className="price">Стоимость<br/>появится позже</p><p className="muted">[Состав пакета, условия участия и способы оплаты будут добавлены.]</p><button className="button" disabled>Покупка скоро откроется <ArrowUpRight size={19}/></button><small>В макете оплата и сбор заявок недоступны.</small></div></section></main>
<footer className="wrap footer"><div className="footer-top"><a className="brand" href="#course"><span className="brand-mark">д.</span><span>ДМИТРИЙ<small>ПРОЕКТ КУРСА</small></span></a><div className="footer-social"><span>На связи</span><div><button disabled>Telegram ↗</button><button disabled>Instagram ↗</button><button disabled>VK ↗</button></div><small>Социальные сети — места для будущих ссылок</small></div><a className="back-top" href="#course">Наверх <ArrowUpRight size={18}/></a></div><div className="legal"><p>© 2026 Дмитрий · Макет образовательной программы.<br/>[ФИО / наименование исполнителя, ИНН и контакты — будут добавлены.]</p><div><span>Оферта — готовится</span><span>Политика конфиденциальности — готовится</span></div><p>Демонстрационная версия. Условия участия не утверждены, продажа не осуществляется. Материалы программы не являются медицинскими рекомендациями.</p></div></footer></>}

